"""empty message

Revision ID: 6084ef619a07
Revises: d76bd11be4d8
Create Date: 2020-11-24 19:28:36.377442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6084ef619a07"
down_revision = "d76bd11be4d8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pblEvents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("className", sa.String(length=50), nullable=True),
        sa.Column("schoolYear", sa.Integer(), nullable=True),
        sa.Column("semester", sa.String(length=20), nullable=True),
        sa.Column("quarter", sa.Integer(), nullable=True),
        sa.Column("pblName", sa.String(length=100), nullable=True),
        sa.Column("eventCategory", sa.String(length=100), nullable=True),
        sa.Column("confirmed", sa.Boolean(), nullable=True),
        sa.Column("eventDate", sa.Date(), nullable=True),
        sa.Column("startTime", sa.Time(), nullable=True),
        sa.Column("endTime", sa.Time(), nullable=True),
        sa.Column("eventLocation", sa.String(length=100), nullable=True),
        sa.Column("eventStreetAddress1", sa.String(length=100), nullable=True),
        sa.Column("eventStreetAddress2", sa.String(length=100), nullable=True),
        sa.Column("eventCity", sa.String(length=100), nullable=True),
        sa.Column("eventState", sa.String(length=100), nullable=True),
        sa.Column("eventZip", sa.String(length=10), nullable=True),
        sa.Column("eventComments", sa.Text(), nullable=True),
        sa.Column("googleCalendarEventID", sa.String(length=250), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pblEvents")),
    )
    op.create_table(
        "pblTeams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("className", sa.String(length=50), nullable=True),
        sa.Column("schoolYear", sa.Integer(), nullable=True),
        sa.Column("semester", sa.String(length=20), nullable=True),
        sa.Column("quarter", sa.Integer(), nullable=True),
        sa.Column("pblNumber", sa.Integer(), nullable=True),
        sa.Column("pblTeamNumber", sa.Integer(), nullable=True),
        sa.Column("chattStateANumber", sa.String(length=20), nullable=False),
        sa.Column("pblName", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["chattStateANumber"],
            ["Student.chattStateANumber"],
            name=op.f("fk_pblTeams_chattStateANumber_Student"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pblTeams")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pblTeams")
    op.drop_table("pblEvents")
    # ### end Alembic commands ###
